# Stage 1: Base Image
FROM python:3.11-slim

# Set environment variables for Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies
RUN apt-get update && apt-get install -y socat && rm -rf /var/lib/apt/lists/*


# Set working directory
WORKDIR /app

# Stage 2: Install Dependencies
# Copy requirements from the specific location
COPY digiliencia/configs/fastAPI/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Stage 3: Copy Application Code
COPY digiliencia/__init__.py ./digiliencia/
COPY digiliencia/agents ./digiliencia/agents
COPY digiliencia/enums ./digiliencia/enums
COPY digiliencia/exc ./digiliencia/exc
COPY digiliencia/utils ./digiliencia/utils
COPY digiliencia/data ./digiliencia/data
COPY digiliencia/configs/env.py ./digiliencia/configs/
COPY digiliencia/configs/fastAPI ./digiliencia/configs/fastAPI

# Set working directory to where main.py and entrypoint.sh reside
WORKDIR /app/digiliencia/configs/fastAPI

# Add /app to PYTHONPATH so 'import digiliencia' works from anywhere
ENV PYTHONPATH=/app


# Expose the port that the Uvicorn server will run on
EXPOSE 8080

# Stage 4: Entrypoint
# Make sure entrypoint script is executable
RUN chmod +x entrypoint.sh

# Command to Run the Application using the entrypoint script
ENTRYPOINT ["./entrypoint.sh"]

