# Stage 1: Base Image
# Use an official, lightweight Python image as a parent.
# 'slim' is a good balance between size and having necessary tools.
FROM python:3.11-slim

# Set environment variables for Python
# 1. Prevents Python from writing .pyc files to the container.
# 2. Ensures that Python output is sent straight to the terminal without buffering.
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Stage 2: Install Dependencies
# Copy the requirements file first. This step is cached by Docker. The cache
# will only be invalidated if requirements.txt changes, speeding up builds.
COPY digiliencia/configs/fastAPI/requirements.txt .

# Install the Python dependencies specified in requirements.txt.
# --no-cache-dir disables the pip cache, which is not needed in a container.
RUN pip install --no-cache-dir -r requirements.txt

# Stage 3: Copy Application Code
# Copy the rest of the application source code from the build context
# into the container's working directory (/app).
# The .dockerignore file will prevent unnecessary files from being copied.
COPY digiliencia/configs/fastAPI .

# Expose the port that the Uvicorn server will run on.
# This is documentation for Docker. The actual port is set in entrypoint.sh.
EXPOSE 8080

# Stage 4: Entrypoint
# Make sure entrypoint script is executable
RUN chmod +x entrypoint.sh

# Command to Run the Application using the entrypoint script
ENTRYPOINT ["./entrypoint.sh"]
