FROM postgres:18.1

RUN apt-get update && apt-get install -y \
    gettext \
    bash \
    && rm -rf /var/lib/apt/lists/*

COPY digiliencia/postgres-db/app-scripts /app-scripts

COPY digiliencia/postgres-db/execute_scripts.sh /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/execute_scripts.sh && \
    chmod -R 755 /app-scripts

EXPOSE 5432
