# /db/models.py
"""
This module defines the SQLAlchemy ORM models for the application's database schema.

It includes models for users, chat conversations, messages, AI prompts (templates),
and AI models.

Key Refactoring Changes:
- Renamed 'IAPrompt' to 'AIPrompt' (English consistency).
- Renamed table 'ia_prompts' to 'ai_prompts'.
- Renamed columns to standard snake_case (e.g., 'AI_name' -> 'name').
"""

import uuid
from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    ForeignKey,
    JSON,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship, declarative_base
from fastapi_users.db import SQLAlchemyBaseUserTableUUID

# The declarative base class for all SQLAlchemy models.
Base = declarative_base()


class User(SQLAlchemyBaseUserTableUUID, Base):
    """
    Represents a registered user in the system.

    Inherits standard authentication fields (email, hashed_password, is_active, etc.)
    from `fastapi-users`.

    Relationships:
        chats (list[Chat]): A list of chat conversations initiated by the user.
    """

    __tablename__ = "users"

    # Relationship: One User -> Many Chats
    # cascade="all, delete-orphan" ensures that if a User is deleted,
    # all their Chat history is also removed from the database.
    chats = relationship("Chat", back_populates="user", cascade="all, delete-orphan")


class Chat(Base):
    """
    Represents a generic chat conversation session.

    A chat belongs to a single user and is initialized with a specific AI Prompt (template).
    It acts as a container for a sequence of Messages.

    Attributes:
        id (UUID): Primary Key.
        title (str): The display title of the conversation.
        user_id (UUID): Foreign Key to the User table.
        ai_prompt_id (UUID): Foreign Key to the AIPrompt table.
    """

    __tablename__ = "chats"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    title = Column(String(255), index=True)

    # Foreign Keys
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    ai_prompt_id = Column(UUID(as_uuid=True), ForeignKey("ai_prompts.id"))

    # Relationships
    user = relationship("User", back_populates="chats")
    ai_prompt = relationship("AIPrompt", back_populates="chats")

    # 'messages' relationship ensures that if a Chat is deleted, messages are gone too.
    messages = relationship(
        "Message", back_populates="chat", cascade="all, delete-orphan"
    )


class AIPrompt(Base):
    """
    Represents a system template or 'Persona' for the AI.

    Examples: "General Assistant", "Code Debugger", "Creative Writer".
    This helps condition the AI before the conversation starts.

    Attributes:
        id (UUID): Primary Key.
        name (str): The display name of the template (e.g., 'Code Helper').
        prompt_text (str): The actual system instruction sent to the LLM.
        description (str): A user-facing description.
    """

    __tablename__ = "ai_prompts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String(255), nullable=False)
    prompt_text = Column(Text, nullable=False)  # Renamed from 'prompt' for clarity
    description = Column(Text, nullable=True)

    # Relationship: One Template -> Many Chats
    chats = relationship("Chat", back_populates="ai_prompt")


class Model(Base):
    """
    Represents a supported Large Language Model (LLM).

    Attributes:
        id (UUID): Primary Key.
        name (str): The unique identifier/name of the model (e.g., 'gpt-4', 'claude-3').
    """

    __tablename__ = "models"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String(255), nullable=False, unique=True)  # Renamed from AI_name

    # Relationship: One Model -> Many Messages (generated by it)
    messages = relationship("Message", back_populates="model")


class Message(Base):
    """
    Represents an individual message within a chat.

    Can be a message from the user or a response from the AI.

    Attributes:
        id (UUID): Primary Key.
        order_number (int): The sequential index of the message in the conversation.
        content (str): The actual text content.
        statistics (JSON): Metadata (tokens usage, latency, etc.).
        chat_id (UUID): Foreign Key to the Chat.
        model_id (UUID): Foreign Key to the Model used (optional, usually for AI responses).
    """

    __tablename__ = "messages"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    order_number = Column(Integer, nullable=False)
    content = Column(Text, nullable=False)
    statistics = Column(JSON, nullable=True)

    # Foreign Keys
    chat_id = Column(UUID(as_uuid=True), ForeignKey("chats.id"), nullable=False)
    model_id = Column(UUID(as_uuid=True), ForeignKey("models.id"), nullable=True)

    # Relationships
    chat = relationship("Chat", back_populates="messages")
    model = relationship("Model", back_populates="messages")
