volumes:
  postgres-data:
  neo4j-data:

networks:
  dev-network:

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspaces/InfraestructuraDiligencia:cached
    command: sleep infinity
    networks:
      - dev-network
    depends_on:
      - db
      - neo4j

  db:
    build:
      context: ..
      dockerfile: digiliencia/configs/postgres-db/DockerFile
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - dev-network

  neo4j:
    image: neo4j:latest
    restart: always
    environment:
      NEO4J_AUTH: neo4j/testpassword
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - neo4j-data:/data
    networks:
      - dev-network

  neo4j-test:
    image: neo4j:latest
    restart: always
    environment:
      NEO4J_AUTH: neo4j/testpassword
    ports:
      - "7475:7474" # HTTP
      - "7688:7687" # Bolt
    networks:
      - dev-network
  embedding-api-service:
      build:
        context: ../services/embeddings
        dockerfile: Dockerfile 
      environment:
        - NVIDIA_VISIBLE_DEVICES=all
      ports:
        - "8000:8000"
      networks:
        - dev-network
      runtime: nvidia
  fastapi-service:
    build:
      context: ..
      dockerfile: digiliencia/configs/fastAPI/DockerFile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - dev-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - dev-network