version: '3.8'

services:

  fastapi-service:
    build:
      context: ..
      dockerfile: digiliencia/configs/fastAPI/DockerFile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - NEO4J_URL=${NEO4J_URL}
      - DDBB_URI=${DDBB_URI}

      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - APP_DB_NAME=${APP_DB_NAME}
      - DB_OWNER_USER=${DB_OWNER_USER}
      - DB_OWNER_PASSWORD=${DB_OWNER_PASSWORD}
      - APP_USER=${APP_USER}
      - APP_USER_PASSWORD=${APP_USER_PASSWORD}
      - APP_USER_LOGIN=${APP_USER_LOGIN}
      - APP_USER_LOGIN_PASSWORD=${APP_USER_LOGIN_PASSWORD}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - WEFORUM_EMAIL=${WEFORUM_EMAIL}
      - WEFORUM_PASSWD=${WEFORUM_PASSWD}
      - LLM_URL=${LLM_URL}
      - CHATBOT_LLM=${CHATBOT_LLM}
      - CLASSIFICATION_MODEL=${CLASSIFICATION_MODEL}
      - EMBEDDINGS_SERVICE=${EMBEDDINGS_SERVICE}
      - EMBEDDINGS_DIMENSION=${EMBEDDINGS_DIMENSION}
    depends_on:
      - db
      - redis
    networks:
      - dev-network

  db:
    build:
      context: ..
      dockerfile: digiliencia/configs/postgres-db/DockerFile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - APP_DB_NAME=${APP_DB_NAME}
      - DB_OWNER_USER=${DB_OWNER_USER}
      - DB_OWNER_PASSWORD=${DB_OWNER_PASSWORD}
      - APP_USER=${APP_USER}
      - APP_USER_PASSWORD=${APP_USER_PASSWORD}
      - APP_USER_LOGIN=${APP_USER_LOGIN}
      - APP_USER_LOGIN_PASSWORD=${APP_USER_LOGIN_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - dev-network

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    #volumes:
    #  - neo4j-data:/data
    networks:
      - dev-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - dev-network

  embedding-api-service:
    image: busybox
    profiles: ["donotstart"] 

  devcontainer:
    image: busybox
    profiles: ["donotstart"]

volumes:
  postgres-data:
  neo4j-data:

networks:
  dev-network: